name: catz
favicon: null
layout_spectrum: 0.16438586497679353
typography_spectrum: 0.91634934511967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5843710694462061
  lightness: 0.36828527692705393
  saturation: 0.08463369077071548
  rhythmicContrast: 0.8944706891197711
purpose: []
